In [1]:
import numpy as np

In [2]:
ar1=np.array(3)

In [3]:
ar1

array(3)

In [4]:
ar2=np.array([2,5,8,1])

In [5]:
ar2

array([2, 5, 8, 1])

In [6]:
ar3=np.array([[1,2,3],[2,3,4]])

In [7]:
ar3

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
#sample programs

# array types 

1.zero array 
2.once array
3.empty array
4.array for range

In [9]:
zero_array=np.zeros(2)

In [10]:
zero_array

array([0., 0.])

In [11]:
ones_array=np.ones((4,2))

In [12]:
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
ar4=np.arange(2,15,2)

In [14]:
ar4

array([ 2,  4,  6,  8, 10, 12, 14])

# transpose

In [15]:
ar5=np.transpose(ar3)

In [16]:
ar5

array([[1, 2],
       [2, 3],
       [3, 4]])

In [17]:
ar6=np.ravel(ar5)

In [18]:
ar6

array([1, 2, 2, 3, 3, 4])

# Concatinate

In [19]:
a1=np.array([2,3])
a2=np.array([3,2])

In [20]:
a1

array([2, 3])

In [21]:
a2

array([3, 2])

In [22]:
concate=np.concatenate([a1,a2])

In [23]:
concate

array([2, 3, 3, 2])

In [24]:
hori=np.vstack((a1,a2))

In [25]:
hori

array([[2, 3],
       [3, 2]])

# Determinant

In [27]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
det_of_mat1=np.linalg.det(mat1)

In [31]:
det_of_mat1

-9.51619735392994e-16

# Inverse

In [32]:
inverse=np.linalg.inv(mat1)

In [33]:
inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [34]:
Dense=np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7],[0,0,1,1]])

In [35]:
Dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 0, 1, 1]])

In [36]:
from scipy.sparse import csr_matrix

In [39]:
sparse=csr_matrix(Dense)

In [40]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [41]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	5
  (2, 2)	6
  (2, 3)	7
  (3, 2)	1
  (3, 3)	1
